# 生成 git-upload.bat（GBK 编码 + CRLF 换行，cmd 最兼容）
# 引号统一用 chr(34) 拼装，避免 bash/Python 多层转义出错
Q = chr(34)  # "

lines = [
    "@echo off",
    "title GRS Git Upload",
    'cd /d "%~dp0"',
    "",
    "echo ========================================",
    "echo   GRS Git Upload - 一键上传 GitHub",
    "echo ========================================",
    "echo.",
    "",
    "echo [1/4] 暂存改动文件...",
    "REM R11/T06: prompt bodies are local-only (prompts/ 正文不进公开仓库)",
    'git add -A -- ":!nul" ":!prompts"',
    "if errorlevel 1 goto :error",
    "REM 仅放行 prompts/README.md 与 *.example.md 骨架（可选，软失败）",
    'git add -- "prompts/README.md" "prompts/*.example.md" >nul 2>nul || echo [WARN] prompts skeletons not staged (optional)',
    "echo [OK] 暂存完成",
    "echo.",
    "",
    "echo [2/4] 敏感文件检查...",
    # /c: 字面匹配；引号包裹模式防止特殊字符解析
    "git diff --cached --name-only | findstr /i /c:" + Q + "config" + Q + " /c:" + Q + "sensitive_words" + Q + " /c:" + Q + ".env" + Q + " /c:" + Q + "prompts" + Q + " >nul",
    "if errorlevel 1 goto :nosensitive",
    "echo.",
    "echo [WARN] 检测到敏感文件被暂存:",
    "echo   config\\default.json / sensitive_words.json / .env",
    "echo   prompts\\*.md (提示词正文必须留在本地，勿提交)",
    "echo   含 API Key/密码/敏感词库/提示词，请检查 .gitignore 后重新执行",
    "echo   确认误报可忽略本警告继续",
    "echo.",
    ":nosensitive",
    "",
    "git diff --cached --quiet",
    "if not errorlevel 1 goto :nocommit",
    "",
    "echo [3/4] 提交改动...",
    'git commit -m "sync: %date% %time%"',
    "if errorlevel 1 goto :error",
    "echo [OK] 提交完成",
    "echo.",
    "",
    "echo [4/4] 推送到 GitHub...",
    "git push origin main",
    "if errorlevel 1 goto :pushfail",
    "goto :pushdone",
    "",
    ":pushfail",
    "echo.",
    "echo [WARN] 普通推送失败，常见原因:",
    "echo   1. 网络不通 - 检查 Clash 节点(浏览器能否打开 google.com)",
    "echo   2. 远程历史与本地不同步(首次同步或远程被改过)",
    "echo.",
    "set \"FORCE=\"",
    "set /p FORCE=强制覆盖远程仓库? 输入 y 确认, 直接回车跳过: ",
    "if /i not \"%FORCE%\"==\"y\" goto :error",
    "echo.",
    "echo 强制推送中(以本地为准覆盖远程)...",
    "git push -f origin main",
    "if errorlevel 1 goto :error",
    "",
    ":pushdone",
    "echo [OK] 推送完成",
    "",
    "echo.",
    "echo ========================================",
    "echo   [OK] 全部完成！已上传到 GitHub",
    "echo ========================================",
    "pause",
    "exit /b 0",
    "",
    ":nocommit",
    "echo.",
    "echo   没有新的改动需要提交",
    "echo   如需拉取远程更新: git pull origin main",
    "echo.",
    "pause",
    "exit /b 0",
    "",
    ":error",
    "echo.",
    "echo ========================================",
    "echo   [FAIL] 操作失败，请查看上方错误信息",
    "echo ========================================",
    "pause",
    "exit /b 1",
]

content = "\r\n".join(lines) + "\r\n"
with open("git-upload.bat", "wb") as f:
    f.write(content.encode("gbk"))
print("OK:", len(content.encode("gbk")), "bytes, GBK + CRLF")
